services:
  test-erc20-app:
    container_name: test-erc20-app
    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      - MODE=DEV
      - ENVIRONMENT=dev

      - PORT=3000
      - DOCS_PATH=docs

      - CHAIN_ID=11155111
      - RPC_URL=https://sepolia.drpc.org
      - CONTRACT_ADDRESS=0x05e9A91A2B72E1cD576503d565F1112f6d025bb0

      - OPERATOR_ADDRESS=YOUR_WALLET_PUBLIC_KEY
      - OPERATOR_ADDRESS_PK=YOUR_WALLET_PRIVATE_KEY

    ports:
      - 3000:3000
